# Generated by Django 3.1.7 on 2021-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_type_1',
            field=models.CharField(choices=[('pretreatment', 'pretreatment'), ('Registrationcount', 'Registrationcount'), ('Preauthorisation', 'Preauthorisation'), ('Dischargestate', 'Dischargestate'), ('Claimphase', 'Claimphase')], max_length=50),
        ),
    ]
