# Generated by Django 3.1.7 on 2021-05-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discription_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discription_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test_3',
        ),
    ]
