# Generated by Django 3.0.5 on 2021-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='discription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test2',
            name='discription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test3',
            name='discription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test4',
            name='discription',
            field=models.CharField(max_length=100),
        ),
    ]
