# Generated by Django 3.0.5 on 2021-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210610_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='test4',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
