# Generated by Django 3.1.7 on 2021-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210508_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status1',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('approvedExcept', 'approvedExcept'), ('other', 'other'), ('caseStartedWithoutApproval', 'caseStartedWithoutApproval'), ('Running', 'Running')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
