# Generated by Django 3.1.7 on 2021-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210527_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='test_4',
            field=models.ImageField(blank=True, null=True, upload_to='testphotos/test4'),
        ),
    ]
