# Generated by Django 3.1.7 on 2021-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patient_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status1',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('approvedExcept', 'approvedExcept'), ('other', 'other'), ('caseStartedWithoutApproval', 'caseStartedWithoutApproval'), ('Running', 'Running'), ('compleated', 'compleated'), ('DischargeUpdated', 'DischargeUpdated'), ('DischargeUpdatePending', 'DischargeUpdatePending'), ('needToApply', 'needToApply'), ('claimApplied', 'claimApplied'), ('claimPending', 'claimPending'), ('claimapproved', 'claimapproved')], max_length=50),
        ),
    ]
