# Generated by Django 3.1.7 on 2021-05-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210501_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discription1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test2',
        ),
    ]
