# Generated by Django 3.0.5 on 2021-07-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210727_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='testname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.test3'),
        ),
    ]
