# Generated by Django 3.1.7 on 2021-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210501_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discription',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='discription1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='test1',
            field=models.ImageField(blank=True, null=True, upload_to='testphotos/test1/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='test2',
            field=models.ImageField(blank=True, null=True, upload_to='testphotos/test2/'),
        ),
    ]
