# Generated by Django 3.0.5 on 2021-09-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_auto_20210902_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='his',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hospital.his'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hospital.his'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='changed_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.his'),
            preserve_default=False,
        ),
    ]
