# Generated by Django 3.0.5 on 2021-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210727_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='test3',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='test4',
            name='Patient',
        ),
        migrations.AddField(
            model_name='test1',
            name='folderName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='names',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
    ]
