# Generated by Django 3.1.7 on 2021-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210501_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='test1',
            field=models.ImageField(default='testphotos/test1/om.jpg', upload_to='testphotos/test1/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='test2',
            field=models.ImageField(default='testphotos/test1/om.jpg', upload_to='testphotos/test2/'),
        ),
    ]
