# Generated by Django 3.0.5 on 2021-09-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210902_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.his'),
        ),
    ]
