# Generated by Django 3.0.5 on 2021-07-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210727_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='test1',
            name='test',
        ),
        migrations.CreateModel(
            name='testphotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ImageField(blank=True, null=True, upload_to='testphotos/test1/')),
                ('discription', models.CharField(max_length=100)),
                ('folderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.test1')),
            ],
        ),
    ]
