# Generated by Django 3.0.5 on 2021-07-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210728_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='testphotos',
            name='Patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
            preserve_default=False,
        ),
    ]
