# Generated by Django 3.0.5 on 2021-10-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210902_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='genaral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=40)),
                ('admitDate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('orthodontist', 'orthodontist'), ('endodontist', 'endodontist'), ('maxillofacialSurgeon', 'maxillofacialSurgeon'), ('prosthodontist', 'prosthodontist'), ('implotology', 'implotology'), ('pedodontist', 'pedodontist'), ('oralmedicine&pathologist', 'oralmedicine&pathologist'), ('other', 'other')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='department',
            field=models.CharField(choices=[('orthodontist', 'orthodontist'), ('endodontist', 'endodontist'), ('maxillofacialSurgeon', 'maxillofacialSurgeon'), ('prosthodontist', 'prosthodontist'), ('implotology', 'implotology'), ('pedodontist', 'pedodontist'), ('oralmedicine&pathologist', 'oralmedicine&pathologist'), ('other', 'other')], default='Cardiologist', max_length=50),
        ),
    ]
