# Generated by Django 3.0.5 on 2021-10-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20211013_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genaral',
            name='photo',
            field=models.TextField(),
        ),
    ]
