# Generated by Django 3.0.5 on 2021-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_testphotos_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='testphotos',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
