# Generated by Django 3.0.5 on 2021-08-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_testphotos_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreatmentCode', models.CharField(max_length=200)),
                ('TreatmentName', models.CharField(max_length=200)),
                ('TreatmentCost', models.CharField(max_length=200)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
    ]
