# Generated by Django 3.0.5 on 2021-08-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_treatmentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabId', models.CharField(max_length=200)),
                ('LabName', models.CharField(max_length=200)),
                ('LabAddress', models.CharField(max_length=200)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
    ]
